language: php
sudo: false
services: mongodb

php:
  - 5.5
  - 5.6
  - 7.0
before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar update
    - curl -sSL https://raw.githubusercontent.com/floriansemm/travis-solr/master/travis-solr.sh | SOLR_CORE=core0 DEBUG=1 SOLR_VERSION=4.8.0 SOLR_CONFS="Tests/Resources/config/schema.xml" bash

script:
    - phpunit
    - ./bin/behat
