language: php

services: mongodb

php:
  - 5.4
  - 5.5
  - 5.6
before_script:
    - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev
    - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.8.0 bash


script:
    - phpunit
    - php behat.phar
notifications:
  email:
    - fsemm.travis-ci@gmx.de    
